FIND_PROGRAM(MPD_BIN mpd)
IF(NOT MPD_BIN)
	MESSAGE(FATAL_ERROR "cannot find mpd binary")
ENDIF()

ADD_DEFINITIONS(-D MPD_BINARY="\\"${MPD_BIN}\\"")
SET_DIRECTORY_PROPERTIES(PROPERTIES COMPILE_DEFINITIONS G_LOG_DOMAIN="dynlist_tests")

ADD_LIBRARY(fixture SHARED fixture_gmpc.c fixture_mpd.c)
TARGET_LINK_LIBRARIES(fixture ${DEPS_LIBRARIES} ${LIBMPD_LIBRARIES})

MACRO(ADD_TEST_CONFIG target def file)
	SET(outfile "${PROJECT_BINARY_DIR}/tests/${file}")
	FILE(READ ${file}.in config_in)
	STRING(REPLACE "DIR_SRC" "${PROJECT_SOURCE_DIR}/tests" config ${config_in})
	STRING(REPLACE "DIR_BIN" "${PROJECT_BINARY_DIR}/tests" config ${config})
	FILE(WRITE ${outfile} ${config})

	GET_TARGET_PROPERTY(prev ${target} COMPILE_DEFINITIONS)
	SET_TARGET_PROPERTIES(${target} PROPERTIES COMPILE_DEFINITIONS "${def}=\"${outfile}\";${prev}")
ENDMACRO()

MACRO(ADD_TEST_DATA target test_name)
	ADD_TEST(${test_name} gtester -k --verbose ${target})
	SET_TESTS_PROPERTIES(${test_name} PROPERTIES PASS_REGULAR_EXPRESSION "PASS")
	SET_TESTS_PROPERTIES(${test_name} PROPERTIES FAIL_REGULAR_EXPRESSION "FAIL")

	SET_TARGET_PROPERTIES(${target} PROPERTIES COMPILE_DEFINITIONS "")
	TARGET_LINK_LIBRARIES(${target} dynlist fixture ${DEPS_LIBRARIES} ${LIBMPD_LIBRARIES})
ENDMACRO()
